name: Build motion

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: login to docker hub
        run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
            TAG=$(cat Dockerfile | grep "ARG TAG" | cut -d "=" -f2)
            docker buildx build --push \
            --tag leograba/motion:latest \
            --tag leograba/motion:${TAG} \
            --platform linux/arm/v7,linux/arm64/v8,linux/amd64 .